server:
  host:
    api: http://localhost:8080
  port: 8080


openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:

spring:
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql : false
    database: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cafe?useSSL=false
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

